### ISSUE TITLE
Reducing boilerplate by decoupling validation logic

### ISSUE THREAD

**Issue by nilliax** [Hackder/toy#1]
First and foremost, thank you for your work, Toy is an outstanding decoding library. I was wandering whether adding some utility functions to decouple validation logic might be a good idea to reduce boilerplate. Here is the approach I take in my use cases. I created following adapters
```Gleam
/// Error Generator allows passing values and generate messages based on provided values
pub type ErrorGenerator(a) {
  ErrorGenerator(
    check: fn(a) -> String,
    expected: fn(a) -> String,
    found: fn(a) -> String,
  )
}

/// Validator generator function
pub fn toy_validator(is_valid: fn(a) -> Bool, error: ErrorGenerator(a)) {
  fn(dec: Decoder(a)) -> Decoder(a) {
    Decoder(fn(data) {
      case dec.run(data) {
        #(default, Ok(data)) ->
          case is_valid(data) {
            True -> #(default, Ok(data))
            False -> #(
              default,
              Error([
                ToyError(
                  error: ValidationFailed(
                    check: error.check(data),
                    expected: error.expected(data),
                    found: error.found(data),
                  ),
                  path: [],
                ),
              ]),
            )
          }
        with_decode_error -> with_decode_error
      }
    })
  }
}
```
Then validation functions can be generated by users using boolean functions and closures, for example
```Gleam
/// Validation logic, boolean function
pub fn min(i: Int, min: Int) {
  min <= i
}

/// toy_validator function used to generate validator, closures used to pass parameters
pub fn toy_min(min: Int) {
  toy_validator(
    fn(i: Int) { min(i, min) },
    ErrorGenerator(
      check: fn(i) { "int_min" },
      expected: fn(i) { "=> " <> int.to_string(min) },
      found: fn(i) { int.to_string(i) },
    ),
  )
}
```
Does not really add any new functionality, just reduces boilerplate. If this might be a good idea, I can try take a dig at it.

**Comment by Hackder** [comment]
Hello, thank you for your suggestion. I think this is almost the same as the built-in `refine` function https://hexdocs.pm/toy/toy.html#refine
Would this provide some functionality that isn't covered by `refine`?

Also, I try to provide all common validation within toy itself, such that building your own validation functions is rare. If your validation use case is general enough, a new built-in validator could be added!

**Comment by nilliax** [comment]
That's true, I did not notice the doc line for that one. Indeed any boolean function return can be adopted to return `Result(Nil, List(ToyError))`, I think that's a better approach, thank you!
